src/index.ts

@Denubis This should fix the conductor not working, let me know if it doesn't work for you.

Listen on all addresses

---

src/authconfig.ts

@Denubis Can you check what hostname is produced on dev? I want to confirm that the right one is being passed in.

Log hostname

---

src/authkeys/user.ts

More logging of send

---

src/authconfig.ts
src/authkeys/user.ts
src/buildconfig.ts
src/couchdb/users.ts

This simply checks if a user is in the required group, otherwise errors.

Add authentication for February

---

src/authkeys/index.test.ts
src/authkeys/signing_keys.ts
src/authkeys/types.ts
src/buildconfig.ts
src/routes.ts
views/send-token.handlebars

This allows reading and checking the token, so that we can show username, roles etc. in the client.

Send pubkey info to client

---

views/send-token.handlebars

Using window.parent should allow webviews to work.

Allow different connections to app

---

views/send-token.handlebars

cordova_iap is added to window when in a cordova inappbroswer.

Send the auth token when in a cordova inappbroswer

---

src/routes.ts
views/home.handlebars

If logged in, the index page shows a logout button to allow users to log
out of the conductor.

Add logout flow

---

src/routes.ts
views/home.handlebars

Hopefully this fixes the template rendering error.

Split out roles in template

---

package-lock.json

Signed-off-by: Brian Ballsun-Stanton <denubis@noreply.users.github.com>

updating package.lock

---

Dockerfile
package-lock.json

no node hash, to see if that changes build quality

---

docker-compose.yml

Building for FAIMS3-544

---

couchdb/initCouchDB.js

@Denubis This should fix the login issue.

Add missing conductor_url to new setup scripts

---

Dockerfile
couchdb/Dockerfile
couchdb/initCouchDB.js
docker-compose.yml
src/buildconfig.ts
src/core.ts

refining environment variables further

---

src/couchdb/users.ts
src/middleware.ts
src/registration.ts
src/routes.ts
views/notebook-landing.handlerbars
views/remove-role-error.handlebars
views/remove-role-success.handlebars
views/remove-role.handlebars

We will want to have a nicer UI later on, but this implements what's
needed at the database level to manage this.

Add basic page for project roles removal

---

package-lock.json
package.json
src/routes.ts

This also includes the changes needed for the upgrade, as well as updates to the typings that need to be in sync.

Update passport to 0.6.0

---

src/auth_providers/google.ts
views/home.handlebars

We should have a nice name and the emails should be in the system.

Fix name and email from new google oauth2

---

src/auth_providers/google.ts
src/buildconfig.ts

This should resolve the current bug raised in FAIMS3-584.

Filter and extract emails from Google profile

---

src/routes.ts
views/home.handlebars

feat: Adding bearer token to Conductor GUI to support exporter

---

src/auth_routes.ts

Use the multiple login prompt for google

---

views/layouts/main.handlebars

Have the FAIMS logo go to home page

---

views/home.handlebars
views/invite.handlebars
views/my-invites.handlebars

This should make the invite flow more obvious.

Add improved UI for invites

---

couchdb/initCouchDB.js
docker-compose.dev.yml
docker-compose.yml

A few tweaks to the deploy files to ensure that bounceFoo continues to work. 

bug: fixing docker deploy files

---

docker-compose.yml
views/send-token.handlebars

removing the word error from send-token

---

deployConductor.sh
docker-compose.dev.yml
src/routes.ts
views/home.handlebars

Added pubkey to token export

---

docker-compose.dev.yml
notebooks/campus-survey.json
package-lock.json
package.json
src/api/routes.ts
src/couchdb/index.ts
src/couchdb/initialise.ts
src/couchdb/notebooks.ts
src/index.ts
src/middleware.ts
test/couchdb.test.ts

Adds api endpoints for notebook data. Uses the faims3-datamodel module refactored from FAIMS3 to access the database and handle records. 
Signed-off-by: Steve Cassidy <steve.cassidy@mq.edu.au>

API endpoint to export notebook data

---

.env.dist
docker-compose.dev.yml
docker-compose.yml
src/api/routes.ts
src/auth_routes.ts
src/buildconfig.ts
src/couchdb/index.ts
src/couchdb/invites.ts
src/couchdb/notebooks.ts
src/couchdb/users.ts
src/index.ts
src/registration.ts
src/routes.ts
test/api.test.ts
test/conductor.test.ts
test/couchdb.test.ts
test/directory.attack.http
test/invites.test.ts
views/cluster-users.handlebars
views/home.handlebars

* Clean up ENV variables, remove those that aren't needed
* Add a way to give a user cluster-admin permissions via the UI
* Notebooks list is not showing all notebooks a user can read

More Admin Cleanup

---

src/buildconfig.ts

Signed-off-by: Steve Cassidy <steve.cassidy@mq.edu.au>

replace hard coded secret with uuid

---

package-lock.json
package.json
src/couchdb/notebooks.ts

Download was tripped up by oddly shaped data, be more robust.
Signed-off-by: Steve Cassidy <steve.cassidy@mq.edu.au>

Fix bug in download

---

package-lock.json
package.json

Signed-off-by: Steve Cassidy <steve.cassidy@mq.edu.au>

upgrade faims3-datamodel
